-- models/medical_claim.sql

SELECT DISTINCT
    CAST(ih.bill_id AS VARCHAR) AS claim_id,
    CAST(id.line_number AS INTEGER) AS claim_line_number,
    'institutional' AS claim_type,
    CAST(MD5(ih.employee_date_of_birth || ih.employee_gender_code) AS VARCHAR) AS patient_id,
    CAST(NULL AS VARCHAR) AS member_id,
    CAST(NULL AS VARCHAR) AS payer,
    CAST(NULL AS VARCHAR) AS plan,
    CAST(ih.reporting_period_start_date AS DATE) AS claim_start_date,
    CAST(ih.reporting_period_end_date AS DATE) AS claim_end_date,
    CAST(id.service_line_from_date AS DATE) AS claim_line_start_date,
    CAST(id.service_line_to_date AS DATE) AS claim_line_end_date,
    CAST(COALESCE(ih.admission_date, ih.service_bill_from_date) AS DATE) AS admission_date,
    CAST(COALESCE(ih.discharge_date, ih.service_bill_to_date) AS DATE) AS discharge_date,
    '1' AS admit_source_code,
    CAST(ih.admission_type_code AS VARCHAR) AS admit_type_code,
    CAST(NULL AS VARCHAR) AS discharge_disposition_code,
    CAST(ih.facility_code AS VARCHAR) AS place_of_service_code,
    CAST(NULL AS VARCHAR) AS bill_type_code,
    CAST(ih.diagnosis_related_group_code AS VARCHAR) AS ms_drg_code,
    CAST(NULL AS VARCHAR) AS apr_drg_code,
    CAST(id.revenue_billed_code AS VARCHAR) AS revenue_center_code,
    CAST(NULL AS INTEGER) AS service_unit_quantity,
    CAST(id.hcpcs_line_procedure_billed AS VARCHAR) AS hcpcs_code,
    CAST(id.first_hcpcs_modifier_billed AS VARCHAR) AS hcpcs_modifier_1,
    CAST(id.second_hcpcs_modifier_billed AS VARCHAR) AS hcpcs_modifier_2,
    CAST(NULL AS VARCHAR) AS hcpcs_modifier_3,
    CAST(NULL AS VARCHAR) AS hcpcs_modifier_4,
    CAST(NULL AS VARCHAR) AS hcpcs_modifier_5,
    CAST(NULL AS VARCHAR) AS rendering_npi,
    CAST(ih.referring_provider_national AS VARCHAR) AS billing_npi,
    CAST(ih.facility_national_provider AS VARCHAR) AS facility_npi,
    CAST(ih.date_insurer_paid_bill AS DATE) AS paid_date,
    CAST(id.total_amount_paid_per_line AS FLOAT) AS paid_amount,
    CAST(NULL AS FLOAT) AS allowed_amount,
    CAST(id.total_charge_per_line AS FLOAT) AS charge_amount,
    CAST(NULL AS FLOAT) AS coinsurance_amount,
    CAST(NULL AS FLOAT) AS copayment_amount,
    CAST(NULL AS FLOAT) AS deductible_amount,
    CAST(ih.total_charge_per_bill AS FLOAT) AS total_cost_amount,
    'icd-10-cm' AS diagnosis_code_type,
    CAST(REPLACE(ih.admitting_diagnosis_code, '.', '') AS VARCHAR) AS diagnosis_code_1,
    CAST(REPLACE(ih.second_icd_9cm_or_icd_10cm, '.', '') AS VARCHAR) AS diagnosis_code_2,
    CAST(REPLACE(ih.third_icd_9cm_or_icd_10cm, '.', '') AS VARCHAR) AS diagnosis_code_3,
    CAST(REPLACE(ih.fourth_icd_9cm_or_icd_10cm, '.', '') AS VARCHAR) AS diagnosis_code_4,
    CAST(REPLACE(ih.fifth_icd_9cm_or_icd_10cm, '.', '') AS VARCHAR) AS diagnosis_code_5,
    CAST(NULL AS VARCHAR) AS diagnosis_code_6,
    CAST(NULL AS VARCHAR) AS diagnosis_code_7,
    CAST(NULL AS VARCHAR) AS diagnosis_code_8,
    CAST(NULL AS VARCHAR) AS diagnosis_code_9,
    CAST(NULL AS VARCHAR) AS diagnosis_code_10,
    CAST(NULL AS VARCHAR) AS diagnosis_code_11,
    CAST(NULL AS VARCHAR) AS diagnosis_code_12,
    CAST(NULL AS VARCHAR) AS diagnosis_code_13,
    CAST(NULL AS VARCHAR) AS diagnosis_code_14,
    CAST(NULL AS VARCHAR) AS diagnosis_code_15,
    CAST(NULL AS VARCHAR) AS diagnosis_code_16,
    CAST(NULL AS VARCHAR) AS diagnosis_code_17,
    CAST(NULL AS VARCHAR) AS diagnosis_code_18,
    CAST(NULL AS VARCHAR) AS diagnosis_code_19,
    CAST(NULL AS VARCHAR) AS diagnosis_code_20,
    CAST(NULL AS VARCHAR) AS diagnosis_code_21,
    CAST(NULL AS VARCHAR) AS diagnosis_code_22,
    CAST(NULL AS VARCHAR) AS diagnosis_code_23,
    CAST(NULL AS VARCHAR) AS diagnosis_code_24,
    CAST(NULL AS VARCHAR) AS diagnosis_code_25,
    'Y' AS diagnosis_poa_1,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_2,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_3,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_4,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_5,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_6,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_7,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_8,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_9,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_10,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_11,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_12,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_13,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_14,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_15,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_16,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_17,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_18,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_19,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_20,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_21,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_22,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_23,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_24,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_25,
    'icd-10-cm' AS procedure_code_type,
    CAST(ih.first_icd_9cm_or_icd_10cm_1 AS VARCHAR) AS procedure_code_1,
    CAST(ih.second_icd_9cm_or_icd_10cm_1 AS VARCHAR) AS procedure_code_2,
    CAST(ih.third_icd_9cm_or_icd_10cm_1 AS VARCHAR) AS procedure_code_3,
    CAST(ih.fourth_icd_9cm_or_icd_10cm_1 AS VARCHAR) AS procedure_code_4,
    CAST(NULL AS VARCHAR) AS procedure_code_5,
    CAST(NULL AS VARCHAR) AS procedure_code_6,
    CAST(NULL AS VARCHAR) AS procedure_code_7,
    CAST(NULL AS VARCHAR) AS procedure_code_8,
    CAST(NULL AS VARCHAR) AS procedure_code_9,
    CAST(NULL AS VARCHAR) AS procedure_code_10,
    CAST(NULL AS VARCHAR) AS procedure_code_11,
    CAST(NULL AS VARCHAR) AS procedure_code_12,
    CAST(NULL AS VARCHAR) AS procedure_code_13,
    CAST(NULL AS VARCHAR) AS procedure_code_14,
    CAST(NULL AS VARCHAR) AS procedure_code_15,
    CAST(NULL AS VARCHAR) AS procedure_code_16,
    CAST(NULL AS VARCHAR) AS procedure_code_17,
    CAST(NULL AS VARCHAR) AS procedure_code_18,
    CAST(NULL AS VARCHAR) AS procedure_code_19,
    CAST(NULL AS VARCHAR) AS procedure_code_20,
    CAST(NULL AS VARCHAR) AS procedure_code_21,
    CAST(NULL AS VARCHAR) AS procedure_code_22,
    CAST(NULL AS VARCHAR) AS procedure_code_23,
    CAST(NULL AS VARCHAR) AS procedure_code_24,
    CAST(NULL AS VARCHAR) AS procedure_code_25,
    CAST(ih.first_procedure_date AS DATE) AS procedure_date_1,
    CAST(ih.second_procedure_date AS DATE) AS procedure_date_2,
    CAST(ih.third_procedure_date AS DATE) AS procedure_date_3,
    CAST(ih.fourth_procedure_date AS DATE) AS procedure_date_4,
    CAST(NULL AS DATE) AS procedure_date_5,
    CAST(NULL AS DATE) AS procedure_date_6,
    CAST(NULL AS DATE) AS procedure_date_7,
    CAST(NULL AS DATE) AS procedure_date_8,
    CAST(NULL AS DATE) AS procedure_date_9,
    CAST(NULL AS DATE) AS procedure_date_10,
    CAST(NULL AS DATE) AS procedure_date_11,
    CAST(NULL AS DATE) AS procedure_date_12,
    CAST(NULL AS DATE) AS procedure_date_13,
    CAST(NULL AS DATE) AS procedure_date_14,
    CAST(NULL AS DATE) AS procedure_date_15,
    CAST(NULL AS DATE) AS procedure_date_16,
    CAST(NULL AS DATE) AS procedure_date_17,
    CAST(NULL AS DATE) AS procedure_date_18,
    CAST(NULL AS DATE) AS procedure_date_19,
    CAST(NULL AS DATE) AS procedure_date_20,
    CAST(NULL AS DATE) AS procedure_date_21,
    CAST(NULL AS DATE) AS procedure_date_22,
    CAST(NULL AS DATE) AS procedure_date_23,
    CAST(NULL AS DATE) AS procedure_date_24,
    CAST(NULL AS DATE) AS procedure_date_25,
    'Texas Department of Insurance, Division of Workers Compensation (DWC)' AS data_source
FROM {{ source('tx', 'institutional_header') }} ih
LEFT JOIN {{ source('tx', 'institutional_detail') }} id ON ih.bill_id = id.bill_id

UNION

SELECT DISTINCT
    CAST(ph.bill_id AS VARCHAR) AS claim_id,
    CAST(pd.line_number AS INTEGER) AS claim_line_number,
    'professional' AS claim_type,
    CAST(MD5(ph.employee_date_of_birth || ph.employee_gender_code) AS VARCHAR) AS patient_id,
    CAST(NULL AS VARCHAR) AS member_id,
    CAST(NULL AS VARCHAR) AS payer,
    CAST(NULL AS VARCHAR) AS plan,
    CAST(ph.reporting_period_start_date AS DATE) AS claim_start_date,
    CAST(ph.reporting_period_end_date AS DATE) AS claim_end_date,
    CAST(pd.service_line_from_date AS DATE) AS claim_line_start_date,
    CAST(pd.service_line_to_date AS DATE) AS claim_line_end_date,
    CAST(NULL AS VARCHAR) AS admission_date,
    CAST(NULL AS VARCHAR) AS discharge_date,
    CAST(NULL AS VARCHAR) AS admit_source_code,
    CAST(NULL AS VARCHAR) AS admit_type_code,
    CAST(NULL AS VARCHAR) AS discharge_disposition_code,
    CAST(pd.place_of_service_line_code AS VARCHAR) AS place_of_service_code,
    CAST(NULL AS VARCHAR) AS bill_type_code,
    CAST(NULL AS VARCHAR) AS ms_drg_code,
    CAST(NULL AS VARCHAR) AS apr_drg_code,
    CAST(NULL AS VARCHAR) AS revenue_center_code,
    CAST(NULL AS INTEGER) AS service_unit_quantity,
    CAST(pd.hcpcs_line_procedure_billed AS VARCHAR) AS hcpcs_code,
    CAST(pd.first_hcpcs_modifier_billed AS VARCHAR) AS hcpcs_modifier_1,
    CAST(pd.second_hcpcs_modifier_billed AS VARCHAR) AS hcpcs_modifier_2,
    CAST(NULL AS VARCHAR) AS hcpcs_modifier_3,
    CAST(NULL AS VARCHAR) AS hcpcs_modifier_4,
    CAST(NULL AS VARCHAR) AS hcpcs_modifier_5,
    CAST(pd.rendering_line_provider AS VARCHAR) AS rendering_npi,
    CAST(ph.billing_provider_national AS VARCHAR) AS billing_npi,
    CAST(ph.facility_national_provider AS VARCHAR) AS facility_npi,
    CAST(ph.date_insurer_paid_bill AS DATE) AS paid_date,
    CAST(ph.total_amount_paid_per_bill AS FLOAT) AS paid_amount,
    CAST(NULL AS FLOAT) AS allowed_amount,
    CAST(pd.total_charge_per_line AS FLOAT) AS charge_amount,
    CAST(NULL AS FLOAT) AS coinsurance_amount,
    CAST(NULL AS FLOAT) AS copayment_amount,
    CAST(NULL AS FLOAT) AS deductible_amount,
    CAST(ph.total_charge_per_bill AS FLOAT) AS total_cost_amount,
    'icd-10-cm' AS diagnosis_code_type,
    CAST(REPLACE(ph.first_icd_9cm_or_icd_10cm, '.', '') AS VARCHAR) AS diagnosis_code_1,
    CAST(REPLACE(ph.second_icd_9cm_or_icd_10cm, '.', '') AS VARCHAR) AS diagnosis_code_2,
    CAST(REPLACE(ph.third_icd_9cm_or_icd_10cm, '.', '') AS VARCHAR) AS diagnosis_code_3,
    CAST(REPLACE(ph.fourth_icd_9cm_or_icd_10cm, '.', '') AS VARCHAR) AS diagnosis_code_4,
    CAST(REPLACE(ph.fifth_icd_9cm_or_icd_10cm, '.', '') AS VARCHAR) AS diagnosis_code_5,
    CAST(NULL AS VARCHAR) AS diagnosis_code_6,
    CAST(NULL AS VARCHAR) AS diagnosis_code_7,
    CAST(NULL AS VARCHAR) AS diagnosis_code_8,
    CAST(NULL AS VARCHAR) AS diagnosis_code_9,
    CAST(NULL AS VARCHAR) AS diagnosis_code_10,
    CAST(NULL AS VARCHAR) AS diagnosis_code_11,
    CAST(NULL AS VARCHAR) AS diagnosis_code_12,
    CAST(NULL AS VARCHAR) AS diagnosis_code_13,
    CAST(NULL AS VARCHAR) AS diagnosis_code_14,
    CAST(NULL AS VARCHAR) AS diagnosis_code_15,
    CAST(NULL AS VARCHAR) AS diagnosis_code_16,
    CAST(NULL AS VARCHAR) AS diagnosis_code_17,
    CAST(NULL AS VARCHAR) AS diagnosis_code_18,
    CAST(NULL AS VARCHAR) AS diagnosis_code_19,
    CAST(NULL AS VARCHAR) AS diagnosis_code_20,
    CAST(NULL AS VARCHAR) AS diagnosis_code_21,
    CAST(NULL AS VARCHAR) AS diagnosis_code_22,
    CAST(NULL AS VARCHAR) AS diagnosis_code_23,
    CAST(NULL AS VARCHAR) AS diagnosis_code_24,
    CAST(NULL AS VARCHAR) AS diagnosis_code_25,
    'Y' AS diagnosis_poa_1,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_2,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_3,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_4,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_5,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_6,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_7,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_8,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_9,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_10,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_11,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_12,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_13,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_14,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_15,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_16,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_17,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_18,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_19,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_20,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_21,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_22,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_23,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_24,
    CAST(NULL AS VARCHAR) AS diagnosis_poa_25,
    'icd-10-cm' AS procedure_code_type,
    CAST(NULL AS VARCHAR) AS procedure_code_1,
    CAST(NULL AS VARCHAR) AS procedure_code_2,
    CAST(NULL AS VARCHAR) AS procedure_code_3,
    CAST(NULL AS VARCHAR) AS procedure_code_4,
    CAST(NULL AS VARCHAR) AS procedure_code_5,
    CAST(NULL AS VARCHAR) AS procedure_code_6,
    CAST(NULL AS VARCHAR) AS procedure_code_7,
    CAST(NULL AS VARCHAR) AS procedure_code_8,
    CAST(NULL AS VARCHAR) AS procedure_code_9,
    CAST(NULL AS VARCHAR) AS procedure_code_10,
    CAST(NULL AS VARCHAR) AS procedure_code_11,
    CAST(NULL AS VARCHAR) AS procedure_code_12,
    CAST(NULL AS VARCHAR) AS procedure_code_13,
    CAST(NULL AS VARCHAR) AS procedure_code_14,
    CAST(NULL AS VARCHAR) AS procedure_code_15,
    CAST(NULL AS VARCHAR) AS procedure_code_16,
    CAST(NULL AS VARCHAR) AS procedure_code_17,
    CAST(NULL AS VARCHAR) AS procedure_code_18,
    CAST(NULL AS VARCHAR) AS procedure_code_19,
    CAST(NULL AS VARCHAR) AS procedure_code_20,
    CAST(NULL AS VARCHAR) AS procedure_code_21,
    CAST(NULL AS VARCHAR) AS procedure_code_22,
    CAST(NULL AS VARCHAR) AS procedure_code_23,
    CAST(NULL AS VARCHAR) AS procedure_code_24,
    CAST(NULL AS VARCHAR) AS procedure_code_25,
    CAST(NULL AS DATE) AS procedure_date_1,
    CAST(NULL AS DATE) AS procedure_date_2,
    CAST(NULL AS DATE) AS procedure_date_3,
    CAST(NULL AS DATE) AS procedure_date_4,
    CAST(NULL AS DATE) AS procedure_date_5,
    CAST(NULL AS DATE) AS procedure_date_6,
    CAST(NULL AS DATE) AS procedure_date_7,
    CAST(NULL AS DATE) AS procedure_date_8,
    CAST(NULL AS DATE) AS procedure_date_9,
    CAST(NULL AS DATE) AS procedure_date_10,
    CAST(NULL AS DATE) AS procedure_date_11,
    CAST(NULL AS DATE) AS procedure_date_12,
    CAST(NULL AS DATE) AS procedure_date_13,
    CAST(NULL AS DATE) AS procedure_date_14,
    CAST(NULL AS DATE) AS procedure_date_15,
    CAST(NULL AS DATE) AS procedure_date_16,
    CAST(NULL AS DATE) AS procedure_date_17,
    CAST(NULL AS DATE) AS procedure_date_18,
    CAST(NULL AS DATE) AS procedure_date_19,
    CAST(NULL AS DATE) AS procedure_date_20,
    CAST(NULL AS DATE) AS procedure_date_21,
    CAST(NULL AS DATE) AS procedure_date_22,
    CAST(NULL AS DATE) AS procedure_date_23,
    CAST(NULL AS DATE) AS procedure_date_24,
    CAST(NULL AS DATE) AS procedure_date_25,
    'Texas Department of Insurance, Division of Workers Compensation (DWC)' AS data_source
FROM {{ source('tx', 'professional_header') }} ph
LEFT JOIN {{ source('tx', 'professional_detail') }} pd ON ph.bill_id = pd.bill_id