{% set exists_institutional_header_current = check_table_exists('raw', 'institutional_header_current') %}
{% set exists_institutional_header_historical = check_table_exists('raw', 'institutional_header_historical') %}
{% set exists_professional_header_current = check_table_exists('raw', 'professional_header_current') %}
{% set exists_professional_header_historical = check_table_exists('raw', 'professional_header_historical') %}
{% set exists_institutional_detail_current = check_table_exists('raw', 'institutional_detail_current') %}
{% set exists_institutional_detail_historical = check_table_exists('raw', 'institutional_detail_historical') %}
{% set exists_professional_detail_current = check_table_exists('raw', 'professional_detail_current') %}
{% set exists_professional_detail_historical = check_table_exists('raw', 'professional_detail_historical') %}

with
{% if exists_institutional_header_current and exists_institutional_detail_current %}
institutional_current as (
    select distinct
        cast(ihc.bill_id as varchar) as claim_id,
        cast(idc.line_number as integer) as claim_line_number,
        'institutional' as claim_type,
        case
            when ihc.patient_account_number is null or trim(ihc.patient_account_number) = ''
            then lpad(
                cast(
                    (
                        hash(
                            concat_ws(
                                '||',
                                coalesce(ihc.employee_mailing_city, ''),
                                coalesce(ihc.employee_mailing_state_code, ''),
                                coalesce(ihc.employee_mailing_postal_code, ''),
                                coalesce(ihc.employee_mailing_country, ''),
                                coalesce(cast(ihc.employee_date_of_birth as varchar), ''),
                                coalesce(ihc.employee_gender_code, '')
                            ),
                            'xxhash64'
                        ) % 1000000000
                    ) as varchar
                ),
                9,
                '0'
            )
            else patient_account_number
        end as person_id,
        cast(null as varchar) as member_id,
        cast(null as varchar) as payer,
        cast(null as varchar) as plan,
        cast(ihc.reporting_period_start_date as date) as claim_start_date,
        cast(ihc.reporting_period_end_date as date) as claim_end_date,
        cast(idc.service_line_from_date as date) as claim_line_start_date,
        cast(idc.service_line_to_date as date) as claim_line_end_date,
        cast(coalesce(ihc.admission_date, ihc.service_bill_from_date) as date) as admission_date,
        cast(coalesce(ihc.discharge_date, ihc.service_bill_to_date) as date) as discharge_date,
        '1' as admit_source_code,
        cast(ihc.admission_type_code as varchar) as admit_type_code,
        cast(null as varchar) as discharge_disposition_code,
        cast(ihc.facility_code as varchar) as place_of_service_code,
        cast(null as varchar) as bill_type_code,
        cast(ihc.diagnosis_related_group_code as varchar) as ms_drg_code,
        cast(null as varchar) as apr_drg_code,
        cast(idc.revenue_billed_code as varchar) as revenue_center_code,
        cast(null as integer) as service_unit_quantity,
        cast(idc.hcpcs_line_procedure_billed as varchar) as hcpcs_code,
        cast(idc.first_hcpcs_modifier_billed as varchar) as hcpcs_modifier_1,
        cast(idc.second_hcpcs_modifier_billed as varchar) as hcpcs_modifier_2,
        cast(null as varchar) as hcpcs_modifier_3,
        cast(null as varchar) as hcpcs_modifier_4,
        cast(null as varchar) as hcpcs_modifier_5,
        cast(null as varchar) as rendering_npi,
        cast(null as varchar) as rendering_tin,
        cast(ihc.referring_provider_national as varchar) as billing_npi,
        cast(null as varchar) as billing_tin,
        cast(ihc.facility_national_provider as varchar) as facility_npi,
        cast(ihc.date_insurer_paid_bill as date) as paid_date,
        cast(idc.total_amount_paid_per_line as float) as paid_amount,
        cast(null as float) as allowed_amount,
        cast(idc.total_charge_per_line as float) as charge_amount,
        cast(null as float) as coinsurance_amount,
        cast(null as float) as copayment_amount,
        cast(null as float) as deductible_amount,
        cast(ihc.total_charge_per_bill as float) as total_cost_amount,
        'icd-10-cm' as diagnosis_code_type,
        cast(replace(ihc.admitting_diagnosis_code, '.', '') as varchar) as diagnosis_code_1,
        cast(replace(ihc.first_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_2,
        cast(replace(ihc.second_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_3,
        cast(replace(ihc.third_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_4,
        cast(replace(ihc.fourth_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_5,
        cast(replace(ihc.fifth_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_6,
        cast(null as varchar) as diagnosis_code_7,
        cast(null as varchar) as diagnosis_code_8,
        cast(null as varchar) as diagnosis_code_9,
        cast(null as varchar) as diagnosis_code_10,
        cast(null as varchar) as diagnosis_code_11,
        cast(null as varchar) as diagnosis_code_12,
        cast(null as varchar) as diagnosis_code_13,
        cast(null as varchar) as diagnosis_code_14,
        cast(null as varchar) as diagnosis_code_15,
        cast(null as varchar) as diagnosis_code_16,
        cast(null as varchar) as diagnosis_code_17,
        cast(null as varchar) as diagnosis_code_18,
        cast(null as varchar) as diagnosis_code_19,
        cast(null as varchar) as diagnosis_code_20,
        cast(null as varchar) as diagnosis_code_21,
        cast(null as varchar) as diagnosis_code_22,
        cast(null as varchar) as diagnosis_code_23,
        cast(null as varchar) as diagnosis_code_24,
        cast(null as varchar) as diagnosis_code_25,
        'Y' as diagnosis_poa_1,
        cast(null as varchar) as diagnosis_poa_2,
        cast(null as varchar) as diagnosis_poa_3,
        cast(null as varchar) as diagnosis_poa_4,
        cast(null as varchar) as diagnosis_poa_5,
        cast(null as varchar) as diagnosis_poa_6,
        cast(null as varchar) as diagnosis_poa_7,
        cast(null as varchar) as diagnosis_poa_8,
        cast(null as varchar) as diagnosis_poa_9,
        cast(null as varchar) as diagnosis_poa_10,
        cast(null as varchar) as diagnosis_poa_11,
        cast(null as varchar) as diagnosis_poa_12,
        cast(null as varchar) as diagnosis_poa_13,
        cast(null as varchar) as diagnosis_poa_14,
        cast(null as varchar) as diagnosis_poa_15,
        cast(null as varchar) as diagnosis_poa_16,
        cast(null as varchar) as diagnosis_poa_17,
        cast(null as varchar) as diagnosis_poa_18,
        cast(null as varchar) as diagnosis_poa_19,
        cast(null as varchar) as diagnosis_poa_20,
        cast(null as varchar) as diagnosis_poa_21,
        cast(null as varchar) as diagnosis_poa_22,
        cast(null as varchar) as diagnosis_poa_23,
        cast(null as varchar) as diagnosis_poa_24,
        cast(null as varchar) as diagnosis_poa_25,
        'icd-10-cm' as procedure_code_type,
        cast(coalesce(ihc.icd_9cm_or_icd_10cm_principal, ihc.first_icd_9cm_or_icd_10cm_1) as varchar) as procedure_code_1,
        cast(ihc.second_icd_9cm_or_icd_10cm_1 as varchar) as procedure_code_2,
        cast(ihc.third_icd_9cm_or_icd_10cm_1 as varchar) as procedure_code_3,
        cast(ihc.fourth_icd_9cm_or_icd_10cm_1 as varchar) as procedure_code_4,
        cast(null as varchar) as procedure_code_5,
        cast(null as varchar) as procedure_code_6,
        cast(null as varchar) as procedure_code_7,
        cast(null as varchar) as procedure_code_8,
        cast(null as varchar) as procedure_code_9,
        cast(null as varchar) as procedure_code_10,
        cast(null as varchar) as procedure_code_11,
        cast(null as varchar) as procedure_code_12,
        cast(null as varchar) as procedure_code_13,
        cast(null as varchar) as procedure_code_14,
        cast(null as varchar) as procedure_code_15,
        cast(null as varchar) as procedure_code_16,
        cast(null as varchar) as procedure_code_17,
        cast(null as varchar) as procedure_code_18,
        cast(null as varchar) as procedure_code_19,
        cast(null as varchar) as procedure_code_20,
        cast(null as varchar) as procedure_code_21,
        cast(null as varchar) as procedure_code_22,
        cast(null as varchar) as procedure_code_23,
        cast(null as varchar) as procedure_code_24,
        cast(null as varchar) as procedure_code_25,
        cast(coalesce(ihc.principal_procedure_date, ihc.first_procedure_date) as date) as procedure_date_1,
        cast(ihc.second_procedure_date as date) as procedure_date_2,
        cast(ihc.third_procedure_date as date) as procedure_date_3,
        cast(ihc.fourth_procedure_date as date) as procedure_date_4,
        cast(null as date) as procedure_date_5,
        cast(null as date) as procedure_date_6,
        cast(null as date) as procedure_date_7,
        cast(null as date) as procedure_date_8,
        cast(null as date) as procedure_date_9,
        cast(null as date) as procedure_date_10,
        cast(null as date) as procedure_date_11,
        cast(null as date) as procedure_date_12,
        cast(null as date) as procedure_date_13,
        cast(null as date) as procedure_date_14,
        cast(null as date) as procedure_date_15,
        cast(null as date) as procedure_date_16,
        cast(null as date) as procedure_date_17,
        cast(null as date) as procedure_date_18,
        cast(null as date) as procedure_date_19,
        cast(null as date) as procedure_date_20,
        cast(null as date) as procedure_date_21,
        cast(null as date) as procedure_date_22,
        cast(null as date) as procedure_date_23,
        cast(null as date) as procedure_date_24,
        cast(null as date) as procedure_date_25,
        cast(null as varchar) as in_network_flag,
        'Texas Department of Insurance, Division of Workers Compensation (DWC)' as data_source,
        'institutional_current' as file_name,
        now() as ingest_datetime
    from {{ source('raw', 'institutional_header_current') }} ihc
    join {{ source('raw', 'institutional_detail_current') }} idc ON ihc.bill_id = idc.bill_id
),
{% endif %}

{% if exists_institutional_header_historical and exists_institutional_detail_historical %}
institutional_historical as (
    select distinct
        cast(ihh.bill_id as varchar) as claim_id,
        cast(idh.line_number as integer) as claim_line_number,
        'institutional' as claim_type,
        case
            when ihh.patient_account_number is null or trim(ihh.patient_account_number) = ''
            then lpad(
                cast(
                    (
                        hash(
                            concat_ws(
                                '||',
                                coalesce(ihh.employee_mailing_city, ''),
                                coalesce(ihh.employee_mailing_state_code, ''),
                                coalesce(ihh.employee_mailing_postal_code, ''),
                                coalesce(ihh.employee_mailing_country, ''),
                                coalesce(cast(ihh.employee_date_of_birth as varchar), ''),
                                coalesce(ihh.employee_gender_code, '')
                            ),
                            'xxhash64'
                        ) % 1000000000
                    ) as varchar
                ),
                9,
                '0'
            )
            else patient_account_number
        end as person_id,
        cast(null as varchar) as member_id,
        cast(null as varchar) as payer,
        cast(null as varchar) as plan,
        cast(ihh.reporting_period_start_date as date) as claim_start_date,
        cast(ihh.reporting_period_end_date as date) as claim_end_date,
        cast(idh.service_line_from_date as date) as claim_line_start_date,
        cast(idh.service_line_to_date as date) as claim_line_end_date,
        cast(coalesce(ihh.admission_date, ihh.service_bill_from_date) as date) as admission_date,
        cast(coalesce(ihh.discharge_date, ihh.service_bill_to_date) as date) as discharge_date,
        '1' as admit_source_code,
        cast(ihh.admission_type_code as varchar) as admit_type_code,
        cast(null as varchar) as discharge_disposition_code,
        cast(ihh.facility_code as varchar) as place_of_service_code,
        cast(null as varchar) as bill_type_code,
        cast(ihh.diagnosis_related_group_code as varchar) as ms_drg_code,
        cast(null as varchar) as apr_drg_code,
        cast(idh.revenue_billed_code as varchar) as revenue_center_code,
        cast(null as integer) as service_unit_quantity,
        cast(idh.hcpcs_line_procedure_billed as varchar) as hcpcs_code,
        cast(idh.first_hcpcs_modifier_billed as varchar) as hcpcs_modifier_1,
        cast(idh.second_hcpcs_modifier_billed as varchar) as hcpcs_modifier_2,
        cast(null as varchar) as hcpcs_modifier_3,
        cast(null as varchar) as hcpcs_modifier_4,
        cast(null as varchar) as hcpcs_modifier_5,
        cast(null as varchar) as rendering_npi,
        cast(null as varchar) as rendering_tin,
        cast(ihh.referring_provider_national as varchar) as billing_npi,
        cast(null as varchar) as billing_tin,
        cast(ihh.facility_national_provider as varchar) as facility_npi,
        cast(ihh.date_insurer_paid_bill as date) as paid_date,
        cast(idh.total_amount_paid_per_line as float) as paid_amount,
        cast(null as float) as allowed_amount,
        cast(idh.total_charge_per_line as float) as charge_amount,
        cast(null as float) as coinsurance_amount,
        cast(null as float) as copayment_amount,
        cast(null as float) as deductible_amount,
        cast(ihh.total_charge_per_bill as float) as total_cost_amount,
        'icd-10-cm' as diagnosis_code_type,
        cast(replace(ihh.admitting_diagnosis_code, '.', '') as varchar) as diagnosis_code_1,
        cast(replace(ihh.first_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_2,
        cast(replace(ihh.second_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_3,
        cast(replace(ihh.third_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_4,
        cast(replace(ihh.fourth_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_5,
        cast(replace(ihh.fifth_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_6,
        cast(null as varchar) as diagnosis_code_7,
        cast(null as varchar) as diagnosis_code_8,
        cast(null as varchar) as diagnosis_code_9,
        cast(null as varchar) as diagnosis_code_10,
        cast(null as varchar) as diagnosis_code_11,
        cast(null as varchar) as diagnosis_code_12,
        cast(null as varchar) as diagnosis_code_13,
        cast(null as varchar) as diagnosis_code_14,
        cast(null as varchar) as diagnosis_code_15,
        cast(null as varchar) as diagnosis_code_16,
        cast(null as varchar) as diagnosis_code_17,
        cast(null as varchar) as diagnosis_code_18,
        cast(null as varchar) as diagnosis_code_19,
        cast(null as varchar) as diagnosis_code_20,
        cast(null as varchar) as diagnosis_code_21,
        cast(null as varchar) as diagnosis_code_22,
        cast(null as varchar) as diagnosis_code_23,
        cast(null as varchar) as diagnosis_code_24,
        cast(null as varchar) as diagnosis_code_25,
        'Y' as diagnosis_poa_1,
        cast(null as varchar) as diagnosis_poa_2,
        cast(null as varchar) as diagnosis_poa_3,
        cast(null as varchar) as diagnosis_poa_4,
        cast(null as varchar) as diagnosis_poa_5,
        cast(null as varchar) as diagnosis_poa_6,
        cast(null as varchar) as diagnosis_poa_7,
        cast(null as varchar) as diagnosis_poa_8,
        cast(null as varchar) as diagnosis_poa_9,
        cast(null as varchar) as diagnosis_poa_10,
        cast(null as varchar) as diagnosis_poa_11,
        cast(null as varchar) as diagnosis_poa_12,
        cast(null as varchar) as diagnosis_poa_13,
        cast(null as varchar) as diagnosis_poa_14,
        cast(null as varchar) as diagnosis_poa_15,
        cast(null as varchar) as diagnosis_poa_16,
        cast(null as varchar) as diagnosis_poa_17,
        cast(null as varchar) as diagnosis_poa_18,
        cast(null as varchar) as diagnosis_poa_19,
        cast(null as varchar) as diagnosis_poa_20,
        cast(null as varchar) as diagnosis_poa_21,
        cast(null as varchar) as diagnosis_poa_22,
        cast(null as varchar) as diagnosis_poa_23,
        cast(null as varchar) as diagnosis_poa_24,
        cast(null as varchar) as diagnosis_poa_25,
        'icd-10-cm' as procedure_code_type,
        cast(coalesce(ihh.icd_9cm_or_icd_10cm_principal, ihh.first_icd_9cm_or_icd_10cm_1) as varchar) as procedure_code_1,
        cast(ihh.second_icd_9cm_or_icd_10cm_1 as varchar) as procedure_code_2,
        cast(ihh.third_icd_9cm_or_icd_10cm_1 as varchar) as procedure_code_3,
        cast(ihh.fourth_icd_9cm_or_icd_10cm_1 as varchar) as procedure_code_4,
        cast(null as varchar) as procedure_code_5,
        cast(null as varchar) as procedure_code_6,
        cast(null as varchar) as procedure_code_7,
        cast(null as varchar) as procedure_code_8,
        cast(null as varchar) as procedure_code_9,
        cast(null as varchar) as procedure_code_10,
        cast(null as varchar) as procedure_code_11,
        cast(null as varchar) as procedure_code_12,
        cast(null as varchar) as procedure_code_13,
        cast(null as varchar) as procedure_code_14,
        cast(null as varchar) as procedure_code_15,
        cast(null as varchar) as procedure_code_16,
        cast(null as varchar) as procedure_code_17,
        cast(null as varchar) as procedure_code_18,
        cast(null as varchar) as procedure_code_19,
        cast(null as varchar) as procedure_code_20,
        cast(null as varchar) as procedure_code_21,
        cast(null as varchar) as procedure_code_22,
        cast(null as varchar) as procedure_code_23,
        cast(null as varchar) as procedure_code_24,
        cast(null as varchar) as procedure_code_25,
        cast(coalesce(ihh.principal_procedure_date, ihh.first_procedure_date) as date) as procedure_date_1,
        cast(ihh.second_procedure_date as date) as procedure_date_2,
        cast(ihh.third_procedure_date as date) as procedure_date_3,
        cast(ihh.fourth_procedure_date as date) as procedure_date_4,
        cast(null as date) as procedure_date_5,
        cast(null as date) as procedure_date_6,
        cast(null as date) as procedure_date_7,
        cast(null as date) as procedure_date_8,
        cast(null as date) as procedure_date_9,
        cast(null as date) as procedure_date_10,
        cast(null as date) as procedure_date_11,
        cast(null as date) as procedure_date_12,
        cast(null as date) as procedure_date_13,
        cast(null as date) as procedure_date_14,
        cast(null as date) as procedure_date_15,
        cast(null as date) as procedure_date_16,
        cast(null as date) as procedure_date_17,
        cast(null as date) as procedure_date_18,
        cast(null as date) as procedure_date_19,
        cast(null as date) as procedure_date_20,
        cast(null as date) as procedure_date_21,
        cast(null as date) as procedure_date_22,
        cast(null as date) as procedure_date_23,
        cast(null as date) as procedure_date_24,
        cast(null as date) as procedure_date_25,
        cast(null as varchar) as in_network_flag,
        'Texas Department of Insurance, Division of Workers Compensation (DWC)' as data_source,
        'institutional_historical' as file_name,
        now() as ingest_datetime
    from {{ source('raw', 'institutional_header_historical') }} ihh
    join {{ source('raw', 'institutional_detail_historical') }} idh ON ihh.bill_id = idh.bill_id
),
{% endif %}

{% if exists_professional_header_current and exists_professional_detail_current %}
professional_current as (
    select distinct
        cast(ph.bill_id as varchar) as claim_id,
        cast(pd.line_number as integer) as claim_line_number,
        'professional' as claim_type,
        case
            when ph.patient_account_number is null or trim(ph.patient_account_number) = ''
            then lpad(
                cast(
                    (
                        hash(
                            concat_ws(
                                '||',
                                coalesce(ph.employee_mailing_city, ''),
                                coalesce(ph.employee_mailing_state_code, ''),
                                coalesce(ph.employee_mailing_postal_code, ''),
                                coalesce(ph.employee_mailing_country, ''),
                                coalesce(cast(ph.employee_date_of_birth as varchar), ''),
                                coalesce(ph.employee_gender_code, '')
                            ),
                            'xxhash64'
                        ) % 1000000000
                    ) as varchar
                ),
                9,
                '0'
            )
            else patient_account_number
        end as person_id,
        cast(null as varchar) as member_id,
        cast(null as varchar) as payer,
        cast(null as varchar) as plan,
        cast(ph.reporting_period_start_date as date) as claim_start_date,
        cast(ph.reporting_period_end_date as date) as claim_end_date,
        cast(pd.service_line_from_date as date) as claim_line_start_date,
        cast(pd.service_line_to_date as date) as claim_line_end_date,
        cast(null as date) as admission_date,
        cast(null as date) as discharge_date,
        cast(null as varchar) as admit_source_code,
        cast(null as varchar) as admit_type_code,
        cast(null as varchar) as discharge_disposition_code,
        cast(pd.place_of_service_line_code as varchar) as place_of_service_code,
        cast(null as varchar) as bill_type_code,
        cast(null as varchar) as ms_drg_code,
        cast(null as varchar) as apr_drg_code,
        cast(null as varchar) as revenue_center_code,
        cast(null as integer) as service_unit_quantity,
        cast(pd.hcpcs_line_procedure_billed as varchar) as hcpcs_code,
        cast(pd.first_hcpcs_modifier_billed as varchar) as hcpcs_modifier_1,
        cast(pd.second_hcpcs_modifier_billed as varchar) as hcpcs_modifier_2,
        cast(null as varchar) as hcpcs_modifier_3,
        cast(null as varchar) as hcpcs_modifier_4,
        cast(null as varchar) as hcpcs_modifier_5,
        cast(pd.rendering_line_provider as varchar) as rendering_npi,
        cast(null as varchar) as rendering_tin,
        cast(ph.billing_provider_national as varchar) as billing_npi,
        cast(null as varchar) as billing_tin,
        cast(ph.facility_national_provider as varchar) as facility_npi,
        cast(ph.date_insurer_paid_bill as date) as paid_date,
        cast(ph.total_amount_paid_per_bill as float) as paid_amount,
        cast(null as float) as allowed_amount,
        cast(pd.total_charge_per_line as float) as charge_amount,
        cast(null as float) as coinsurance_amount,
        cast(null as float) as copayment_amount,
        cast(null as float) as deductible_amount,
        cast(ph.total_charge_per_bill as float) as total_cost_amount,
        'icd-10-cm' as diagnosis_code_type,
        cast(replace(ph.first_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_1,
        cast(replace(ph.second_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_2,
        cast(replace(ph.third_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_3,
        cast(replace(ph.fourth_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_4,
        cast(replace(ph.fifth_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_5,
        cast(null as varchar) as diagnosis_code_6,
        cast(null as varchar) as diagnosis_code_7,
        cast(null as varchar) as diagnosis_code_8,
        cast(null as varchar) as diagnosis_code_9,
        cast(null as varchar) as diagnosis_code_10,
        cast(null as varchar) as diagnosis_code_11,
        cast(null as varchar) as diagnosis_code_12,
        cast(null as varchar) as diagnosis_code_13,
        cast(null as varchar) as diagnosis_code_14,
        cast(null as varchar) as diagnosis_code_15,
        cast(null as varchar) as diagnosis_code_16,
        cast(null as varchar) as diagnosis_code_17,
        cast(null as varchar) as diagnosis_code_18,
        cast(null as varchar) as diagnosis_code_19,
        cast(null as varchar) as diagnosis_code_20,
        cast(null as varchar) as diagnosis_code_21,
        cast(null as varchar) as diagnosis_code_22,
        cast(null as varchar) as diagnosis_code_23,
        cast(null as varchar) as diagnosis_code_24,
        cast(null as varchar) as diagnosis_code_25,
        'Y' as diagnosis_poa_1,
        cast(null as varchar) as diagnosis_poa_2,
        cast(null as varchar) as diagnosis_poa_3,
        cast(null as varchar) as diagnosis_poa_4,
        cast(null as varchar) as diagnosis_poa_5,
        cast(null as varchar) as diagnosis_poa_6,
        cast(null as varchar) as diagnosis_poa_7,
        cast(null as varchar) as diagnosis_poa_8,
        cast(null as varchar) as diagnosis_poa_9,
        cast(null as varchar) as diagnosis_poa_10,
        cast(null as varchar) as diagnosis_poa_11,
        cast(null as varchar) as diagnosis_poa_12,
        cast(null as varchar) as diagnosis_poa_13,
        cast(null as varchar) as diagnosis_poa_14,
        cast(null as varchar) as diagnosis_poa_15,
        cast(null as varchar) as diagnosis_poa_16,
        cast(null as varchar) as diagnosis_poa_17,
        cast(null as varchar) as diagnosis_poa_18,
        cast(null as varchar) as diagnosis_poa_19,
        cast(null as varchar) as diagnosis_poa_20,
        cast(null as varchar) as diagnosis_poa_21,
        cast(null as varchar) as diagnosis_poa_22,
        cast(null as varchar) as diagnosis_poa_23,
        cast(null as varchar) as diagnosis_poa_24,
        cast(null as varchar) as diagnosis_poa_25,
        'icd-10-cm' as procedure_code_type,
        cast(null as varchar) as procedure_code_1,
        cast(null as varchar) as procedure_code_2,
        cast(null as varchar) as procedure_code_3,
        cast(null as varchar) as procedure_code_4,
        cast(null as varchar) as procedure_code_5,
        cast(null as varchar) as procedure_code_6,
        cast(null as varchar) as procedure_code_7,
        cast(null as varchar) as procedure_code_8,
        cast(null as varchar) as procedure_code_9,
        cast(null as varchar) as procedure_code_10,
        cast(null as varchar) as procedure_code_11,
        cast(null as varchar) as procedure_code_12,
        cast(null as varchar) as procedure_code_13,
        cast(null as varchar) as procedure_code_14,
        cast(null as varchar) as procedure_code_15,
        cast(null as varchar) as procedure_code_16,
        cast(null as varchar) as procedure_code_17,
        cast(null as varchar) as procedure_code_18,
        cast(null as varchar) as procedure_code_19,
        cast(null as varchar) as procedure_code_20,
        cast(null as varchar) as procedure_code_21,
        cast(null as varchar) as procedure_code_22,
        cast(null as varchar) as procedure_code_23,
        cast(null as varchar) as procedure_code_24,
        cast(null as varchar) as procedure_code_25,
        cast(null as date) as procedure_date_1,
        cast(null as date) as procedure_date_2,
        cast(null as date) as procedure_date_3,
        cast(null as date) as procedure_date_4,
        cast(null as date) as procedure_date_5,
        cast(null as date) as procedure_date_6,
        cast(null as date) as procedure_date_7,
        cast(null as date) as procedure_date_8,
        cast(null as date) as procedure_date_9,
        cast(null as date) as procedure_date_10,
        cast(null as date) as procedure_date_11,
        cast(null as date) as procedure_date_12,
        cast(null as date) as procedure_date_13,
        cast(null as date) as procedure_date_14,
        cast(null as date) as procedure_date_15,
        cast(null as date) as procedure_date_16,
        cast(null as date) as procedure_date_17,
        cast(null as date) as procedure_date_18,
        cast(null as date) as procedure_date_19,
        cast(null as date) as procedure_date_20,
        cast(null as date) as procedure_date_21,
        cast(null as date) as procedure_date_22,
        cast(null as date) as procedure_date_23,
        cast(null as date) as procedure_date_24,
        cast(null as date) as procedure_date_25,
        cast(null as varchar) as in_network_flag,
        'Texas Department of Insurance, Division of Workers Compensation (DWC)' as data_source,
        'professional_current' as file_name,
        now() as ingest_datetime
    from {{ source('raw', 'professional_header_current') }} ph
    join {{ source('raw', 'professional_detail_current') }} pd ON ph.bill_id = pd.bill_id
),
{% endif %}

{% if exists_professional_header_historical and exists_professional_detail_historical %}
professional_historical as (
    select distinct
        cast(phh.bill_id as varchar) as claim_id,
        cast(pdh.line_number as integer) as claim_line_number,
        'professional' as claim_type,
        case
            when phh.patient_account_number is null or trim(phh.patient_account_number) = ''
            then lpad(
                cast(
                    (
                        hash(
                            concat_ws(
                                '||',
                                coalesce(phh.employee_mailing_city, ''),
                                coalesce(phh.employee_mailing_state_code, ''),
                                coalesce(phh.employee_mailing_postal_code, ''),
                                coalesce(phh.employee_mailing_country, ''),
                                coalesce(cast(phh.employee_date_of_birth as varchar), ''),
                                coalesce(phh.employee_gender_code, '')
                            ),
                            'xxhash64'
                        ) % 1000000000
                    ) as varchar
                ),
                9,
                '0'
            )
            else patient_account_number
        end as person_id,
        cast(null as varchar) as member_id,
        cast(null as varchar) as payer,
        cast(null as varchar) as plan,
        cast(phh.reporting_period_start_date as date) as claim_start_date,
        cast(phh.reporting_period_end_date as date) as claim_end_date,
        cast(pdh.service_line_from_date as date) as claim_line_start_date,
        cast(pdh.service_line_to_date as date) as claim_line_end_date,
        cast(null as date) as admission_date,
        cast(null as date) as discharge_date,
        cast(null as varchar) as admit_source_code,
        cast(null as varchar) as admit_type_code,
        cast(null as varchar) as discharge_disposition_code,
        cast(pdh.place_of_service_line_code as varchar) as place_of_service_code,
        cast(null as varchar) as bill_type_code,
        cast(null as varchar) as ms_drg_code,
        cast(null as varchar) as apr_drg_code,
        cast(null as varchar) as revenue_center_code,
        cast(null as integer) as service_unit_quantity,
        cast(pdh.hcpcs_line_procedure_billed as varchar) as hcpcs_code,
        cast(pdh.first_hcpcs_modifier_billed as varchar) as hcpcs_modifier_1,
        cast(pdh.second_hcpcs_modifier_billed as varchar) as hcpcs_modifier_2,
        cast(null as varchar) as hcpcs_modifier_3,
        cast(null as varchar) as hcpcs_modifier_4,
        cast(null as varchar) as hcpcs_modifier_5,
        cast(pdh.rendering_line_provider as varchar) as rendering_npi,
        cast(null as varchar) as rendering_tin,
        cast(phh.billing_provider_national as varchar) as billing_npi,
        cast(null as varchar) as billing_tin,
        cast(phh.facility_national_provider as varchar) as facility_npi,
        cast(phh.date_insurer_paid_bill as date) as paid_date,
        cast(phh.total_amount_paid_per_bill as float) as paid_amount,
        cast(null as float) as allowed_amount,
        cast(pdh.total_charge_per_line as float) as charge_amount,
        cast(null as float) as coinsurance_amount,
        cast(null as float) as copayment_amount,
        cast(null as float) as deductible_amount,
        cast(phh.total_charge_per_bill as float) as total_cost_amount,
        'icd-10-cm' as diagnosis_code_type,
        cast(replace(phh.first_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_1,
        cast(replace(phh.second_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_2,
        cast(replace(phh.third_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_3,
        cast(replace(phh.fourth_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_4,
        cast(replace(phh.fifth_icd_9cm_or_icd_10cm, '.', '') as varchar) as diagnosis_code_5,
        cast(null as varchar) as diagnosis_code_6,
        cast(null as varchar) as diagnosis_code_7,
        cast(null as varchar) as diagnosis_code_8,
        cast(null as varchar) as diagnosis_code_9,
        cast(null as varchar) as diagnosis_code_10,
        cast(null as varchar) as diagnosis_code_11,
        cast(null as varchar) as diagnosis_code_12,
        cast(null as varchar) as diagnosis_code_13,
        cast(null as varchar) as diagnosis_code_14,
        cast(null as varchar) as diagnosis_code_15,
        cast(null as varchar) as diagnosis_code_16,
        cast(null as varchar) as diagnosis_code_17,
        cast(null as varchar) as diagnosis_code_18,
        cast(null as varchar) as diagnosis_code_19,
        cast(null as varchar) as diagnosis_code_20,
        cast(null as varchar) as diagnosis_code_21,
        cast(null as varchar) as diagnosis_code_22,
        cast(null as varchar) as diagnosis_code_23,
        cast(null as varchar) as diagnosis_code_24,
        cast(null as varchar) as diagnosis_code_25,
        'Y' as diagnosis_poa_1,
        cast(null as varchar) as diagnosis_poa_2,
        cast(null as varchar) as diagnosis_poa_3,
        cast(null as varchar) as diagnosis_poa_4,
        cast(null as varchar) as diagnosis_poa_5,
        cast(null as varchar) as diagnosis_poa_6,
        cast(null as varchar) as diagnosis_poa_7,
        cast(null as varchar) as diagnosis_poa_8,
        cast(null as varchar) as diagnosis_poa_9,
        cast(null as varchar) as diagnosis_poa_10,
        cast(null as varchar) as diagnosis_poa_11,
        cast(null as varchar) as diagnosis_poa_12,
        cast(null as varchar) as diagnosis_poa_13,
        cast(null as varchar) as diagnosis_poa_14,
        cast(null as varchar) as diagnosis_poa_15,
        cast(null as varchar) as diagnosis_poa_16,
        cast(null as varchar) as diagnosis_poa_17,
        cast(null as varchar) as diagnosis_poa_18,
        cast(null as varchar) as diagnosis_poa_19,
        cast(null as varchar) as diagnosis_poa_20,
        cast(null as varchar) as diagnosis_poa_21,
        cast(null as varchar) as diagnosis_poa_22,
        cast(null as varchar) as diagnosis_poa_23,
        cast(null as varchar) as diagnosis_poa_24,
        cast(null as varchar) as diagnosis_poa_25,
        'icd-10-cm' as procedure_code_type,
        cast(null as varchar) as procedure_code_1,
        cast(null as varchar) as procedure_code_2,
        cast(null as varchar) as procedure_code_3,
        cast(null as varchar) as procedure_code_4,
        cast(null as varchar) as procedure_code_5,
        cast(null as varchar) as procedure_code_6,
        cast(null as varchar) as procedure_code_7,
        cast(null as varchar) as procedure_code_8,
        cast(null as varchar) as procedure_code_9,
        cast(null as varchar) as procedure_code_10,
        cast(null as varchar) as procedure_code_11,
        cast(null as varchar) as procedure_code_12,
        cast(null as varchar) as procedure_code_13,
        cast(null as varchar) as procedure_code_14,
        cast(null as varchar) as procedure_code_15,
        cast(null as varchar) as procedure_code_16,
        cast(null as varchar) as procedure_code_17,
        cast(null as varchar) as procedure_code_18,
        cast(null as varchar) as procedure_code_19,
        cast(null as varchar) as procedure_code_20,
        cast(null as varchar) as procedure_code_21,
        cast(null as varchar) as procedure_code_22,
        cast(null as varchar) as procedure_code_23,
        cast(null as varchar) as procedure_code_24,
        cast(null as varchar) as procedure_code_25,
        cast(null as date) as procedure_date_1,
        cast(null as date) as procedure_date_2,
        cast(null as date) as procedure_date_3,
        cast(null as date) as procedure_date_4,
        cast(null as date) as procedure_date_5,
        cast(null as date) as procedure_date_6,
        cast(null as date) as procedure_date_7,
        cast(null as date) as procedure_date_8,
        cast(null as date) as procedure_date_9,
        cast(null as date) as procedure_date_10,
        cast(null as date) as procedure_date_11,
        cast(null as date) as procedure_date_12,
        cast(null as date) as procedure_date_13,
        cast(null as date) as procedure_date_14,
        cast(null as date) as procedure_date_15,
        cast(null as date) as procedure_date_16,
        cast(null as date) as procedure_date_17,
        cast(null as date) as procedure_date_18,
        cast(null as date) as procedure_date_19,
        cast(null as date) as procedure_date_20,
        cast(null as date) as procedure_date_21,
        cast(null as date) as procedure_date_22,
        cast(null as date) as procedure_date_23,
        cast(null as date) as procedure_date_24,
        cast(null as date) as procedure_date_25,
        cast(null as varchar) as in_network_flag,
        'Texas Department of Insurance, Division of Workers Compensation (DWC)' as data_source,
        'professional_historical' as file_name,
        now() as ingest_datetime
    from {{ source('raw', 'professional_header_historical') }} phh
    join {{ source('raw', 'professional_detail_historical') }} pdh ON phh.bill_id = pdh.bill_id
)
{% endif %}

select *
from
(
    {% if exists_institutional_header_current and exists_institutional_detail_current %}
        select * from institutional_current
        {% if exists_institutional_header_historical and exists_institutional_detail_historical %}
            union
            select * from institutional_historical
        {% endif %}
        {% if exists_professional_header_current and exists_professional_detail_current %}
            union
            select * from professional_current
        {% endif %}
        {% if exists_professional_header_historical and exists_professional_detail_historical %}
            union
            select * from professional_historical
        {% endif %}
    {% elif exists_institutional_header_historical and exists_institutional_detail_historical %}
        select * from institutional_historical
        {% if exists_professional_header_current and exists_professional_detail_current %}
            union
            select * from professional_current
        {% endif %}
        {% if exists_professional_header_historical and exists_professional_detail_historical %}
            union
            select * from professional_historical
        {% endif %}
    {% elif exists_professional_header_current and exists_professional_detail_current %}
        select * from professional_current
        {% if exists_professional_header_historical and exists_professional_detail_historical %}
            union
            select * from professional_historical
        {% endif %}
    {% endif %}
)